# Assignment 2: Leaflet Map
#### Peter A Dunham


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Clickable Map

Click on county below and pop-up will appear with county name. This map can be expanded to include statistics related to differences in county.  

```{r,  echo=FALSE, warning=FALSE, message=FALSE}
county<-function(){
  
  #https://rstudio.github.io/leaflet/shapes.html
  
  library(rgdal)
  library(magrittr)
  library(leaflet)
  library(jsonlite)
  
  # From https://www.census.gov/geo/maps-data/data/cbf/cbf_state.html
  states <- readOGR("county/cb_2015_us_county_20m.shp",
                    layer = "cb_2015_us_county_20m", GDAL1_integer64_policy = TRUE, verbose=FALSE)
  
  Statekey<-read.csv('STATEFPtoSTATENAME_Key.csv', colClasses=c('character'))
  states<-merge(x=states, y=Statekey, by="STATEFP", all=TRUE)
  
  neStates <- subset(states, states$STATENAME %in% c(
    "Florida"
  ))
  
  states<-merge(x=states, y=Statekey, by="STATEFP", all=TRUE)
  leaflet(neStates) %>%
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
                opacity = 1.0, fillOpacity = 0.5,
                fillColor = ~colorQuantile("YlOrRd", AWATER)(AWATER),
                highlightOptions = highlightOptions(color = "white", weight = 2,
                                                    bringToFront = TRUE),
                popup=~NAME)

  
}
county()
```

#### February 24, 2017

#### For Developing Data Products Data Science Specialization John Hopkins on Coursera



